---
- name: V2ray
  hosts: selfhost
  gather_facts: true
  become: true

  vars_prompt:
    - name: v2ray_ver
      prompt: "V2Ray version"
      default: "4.21.3"
      private: no
    - name: v2ray_arch
      prompt: "V2Ray arch"
      default: "64"
      private: no

  roles:
    - role: v2rayUpgrade
      app_ver: "{{ v2ray_ver }}"
      app_arch: "{{ v2ray_arch }}"