---
- name: ensure directory exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/v2ray
    - /etc/v2ray

- name: stop v2ray service
  systemd:
    name: v2ray
    state: stopped

- name: get v2ray binary package
  unarchive:
    src: "https://github.com/v2ray/v2ray-core/releases/download/v{{ app_ver }}/v2ray-linux-{{ app_arch }}.zip"
    dest: /opt/v2ray
    remote_src: yes

- name: symlink binary files
  file:
    src: "/opt/v2ray/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
  loop:
    - v2ray
    - v2ctl
  notify:
    - restart v2ray

- name: enable v2ray service
  systemd:
    name: v2ray
    state: started
    daemon_reload: yes
    enabled: yes
